quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/test-schedule

  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
